FROM centos:latest
MAINTAINER onkarrenake123@gmail.com
RUN yum install -y httpd \
zip\
unzip
ADD https://www.free-css.com/assets/files/free-css-templates/download/page291/dozecafe.zip /var/www/html/
WORKDIR /var/www/html/
RUN unzip dozecafe.zip
RUN cp -rvf dozecafe/* .
RUN rm -rvf  dozecafe dozecafe.zip
CMD ["/usr/sbin/httpd","-D","FOREGROUND"]
EXPOSE 80